import React from 'react'

export default function Child2() {
  return (
    <>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
        <div>abnbcd</div>
    </>
  )
}
